---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: infrastructure
spec:
  interval: 1m
  url: https://charts.external-secrets.io

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: infrastructure
spec:
  interval: 1m
  targetNamespace: external-secrets
  chart:
    spec:
      chart: external-secrets
      version: '0.5.4'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 1m
  values:
    installCRDs: true