---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    test-substitute: "${label}"
    test-substitute-from-secret: "${label-from-secret}"
    test-substitute-from-configmap: "${label-from-configmap}"