---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/clusters/api/local
  prune: true
  postBuild:
    substitute:
      label: this-is-a-test      
    substituteFrom:
      - kind: ConfigMap
        name: tf-output
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true
      - kind: Secret
        name: tf-output